#include <stdio.h>
#include <eddiso/man.h>

void man(){
    printf("\n"
           "NAME\n"
           "\teddiso\tHarvest ISO19139 XML metadata records from Erddap (TM)\n"
           "\t\tscientific data server instances."
           "\n\n"
           "SYNOPSIS\n"
           "\teddiso --awesome URL | --help | --server URL OUTDIR | --version"
           "\n\n"
           "DESCRIPTION\n"
           "\teddiso harvests the ISO19139 XML metadata records from an\n"
           "\tinstance of the Erddap (TM) scientific data server to a given\n"
           "\tdirectory, for the purposes of building an Open Geospatial\n"
           "\tConsortium (OGC) Catalogue Service for the Web, or other\n"
           "\tOGC Application Programming Interface implementation, based on\n"
           "\tthe content of that Erddap (TM) instance. eddiso can also\n"
           "\tsuggest a list of Erddap servers to harvest metadata records\n"
           "\tfrom."
           "\n\n"
           "\t--awesome URL\n"
           "\t\tUse the Awesome List of Erddap (TM) servers on GitHub\n"
           "\t\tat the supplied URL to suggest locations from which\n"
           "\t\tISO19139 XML metadata records may be harvested. Output is\n"
           "\t\treturned to the screen."
           "\n\n"
           "\t--help\t Display this help page and exit."
           "\n\n"
           "\t--server URL OUTDIR\n"
           "\t\t"
           "\n\n"
           "\t--version\n"
           "\t\tDisplay version information and exit."
           "\n\n"
           "OPTIONS\n"
           "\tOUTDIR\tThe location to which ISO19139 XML records will\n"
           "\t\tharvested."
           "\n\n"
           "\tURL\tThe web address to either an Awesome List of Erddap\n"
           "\t\t(TM) servers or to an instance of the Erddap (TM)\n"
           "\t\tscientfic data server."
           "\n\n");
}